apiVersion: 1

datasources:
  - name: OLAP
    uid: olap
    type: grafana-postgresql-datasource
    access: proxy
    url: analytics:5432
    user: $OLAP_DB_USER
    isDefault: true
    editable: false
    jsonData:
      database: $OLAP_DB_NAME
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
    secureJsonData:
      password: $OLAP_DB_PASSWORD
